/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aavi Jit
 */
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import net.proteanit.sql.DbUtils;


public class base_window extends javax.swing.JFrame{
      Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;

    /**
     * Creates new form base_window
     */
    public base_window() {
        super("Base Window");
        addLookAndFeel();
        initComponents();
        setPosition();
        setVisible(true);
        conn = connectjava.ConnectDb();
        
        
    }
     public void addLookAndFeel() {
         try {
            // select Look and Feel
             UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
             //com.jtattoo.plaf.texture.TextureLookAndFeel
             //com.jtattoo.plaf.hifi.HiFiLookAndFeel
             //com.jtattoo.plaf.noire.NoireLookAndFeel
             //com.jtattoo.plaf.aero.AeroLookAndFeel
                     

            // start application
            
        }
        catch (Exception ex) {
            ex.printStackTrace();
        }
    }
     

      private void setPosition() {

        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension screanSize = toolkit.getScreenSize();

        int screanHeight = screanSize.height;
        int screanWidth = screanSize.width;
        setLocation(screanWidth / 4, screanHeight / 10);

    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        indoor_patient = new javax.swing.JMenuItem();
        outdoor_patient = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        release_patient = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        parmanent_doctor = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        staff_entry = new javax.swing.JMenuItem();
        admin_entry = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        search_doc = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        Indoor_Patient = new javax.swing.JMenuItem();
        Outdoor_patient = new javax.swing.JMenuItem();
        search_staff = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        doc_info = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        aboutUsItem = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("jMenu3");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital.png"))); // NOI18N

        jMenu1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        jMenu1.setText("Patient Entry");

        indoor_patient.setText("Indoor Patient");
        indoor_patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indoor_patientActionPerformed(evt);
            }
        });
        jMenu1.add(indoor_patient);

        outdoor_patient.setText("Outdoor Patient");
        outdoor_patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outdoor_patientActionPerformed(evt);
            }
        });
        jMenu1.add(outdoor_patient);

        jMenuItem5.setText("Patient Bill");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        release_patient.setText("Release Patient");
        release_patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                release_patientActionPerformed(evt);
            }
        });
        jMenu1.add(release_patient);

        jMenuBar1.add(jMenu1);

        jMenu2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 11))); // NOI18N
        jMenu2.setText("Doctor Entry");

        parmanent_doctor.setText("Parmanent Doctor");
        parmanent_doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parmanent_doctorActionPerformed(evt);
            }
        });
        jMenu2.add(parmanent_doctor);

        jMenuBar1.add(jMenu2);

        jMenu4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));
        jMenu4.setText("Staff Entry");

        staff_entry.setText("Staff");
        staff_entry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staff_entryActionPerformed(evt);
            }
        });
        jMenu4.add(staff_entry);

        admin_entry.setText("Administrator");
        admin_entry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_entryActionPerformed(evt);
            }
        });
        jMenu4.add(admin_entry);

        jMenuBar1.add(jMenu4);

        jMenu5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));
        jMenu5.setText("Search");

        search_doc.setText("Doctor");
        search_doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_docActionPerformed(evt);
            }
        });
        jMenu5.add(search_doc);

        jMenu9.setText("Patient");

        Indoor_Patient.setText("Indoor Patient");
        Indoor_Patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Indoor_PatientActionPerformed(evt);
            }
        });
        jMenu9.add(Indoor_Patient);

        Outdoor_patient.setText("Outdoor Patient");
        Outdoor_patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Outdoor_patientActionPerformed(evt);
            }
        });
        jMenu9.add(Outdoor_patient);

        jMenu5.add(jMenu9);

        search_staff.setText("Staff");
        search_staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_staffActionPerformed(evt);
            }
        });
        jMenu5.add(search_staff);

        jMenuBar1.add(jMenu5);

        jMenu7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""))));
        jMenu7.setText("Information");

        doc_info.setText("Doctor");
        doc_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_infoActionPerformed(evt);
            }
        });
        jMenu7.add(doc_info);

        jMenu8.setText("Patient");

        jMenuItem3.setText("Indoor Patient");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem3);

        jMenuItem4.setText("Outdoor Patient");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem4);

        jMenu7.add(jMenu8);

        jMenuItem9.setText("Staff");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem9);

        jMenuBar1.add(jMenu7);

        jMenu6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));
        jMenu6.setText("About Us");

        aboutUsItem.setText("About Us");
        aboutUsItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutUsItemActionPerformed(evt);
            }
        });
        jMenu6.add(aboutUsItem);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
      StaffInfoTable sit= new StaffInfoTable();
      sit.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void aboutUsItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutUsItemActionPerformed
        JOptionPane.showMessageDialog(this,"Avijit Barua\n"
                    + "Roll. No: ASH1201010M\n"
                    + "Dept. of CSTE\n"
                    + "NSTU\n"
                    + "Mob: 01812020827\n"
                    + "E-mail: avijit_barua@hotmail.com\n\n"
                    
                    + "Md. Shakhawat Hossain\n"
                    + "Roll. No: ASH1201029M\n"
                    + "Dept. of CSTE\n"
                    + "NSTU\n"
                    + "Mob: 01820127683\n\n"
                    
                     + "Md. Md. Amran Hossain\n"
                    + "Roll. No: ASH1201036M\n"
                    + "Dept. of CSTE\n"
                    + "NSTU\n"
                    + "Mob: 01743168695"
        
                    );// TODO add your handling code here:
    }//GEN-LAST:event_aboutUsItemActionPerformed

    private void staff_entryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staff_entryActionPerformed
        StaffEntryForm sep =new StaffEntryForm();
        sep.setVisible(true);
    }//GEN-LAST:event_staff_entryActionPerformed

    private void indoor_patientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indoor_patientActionPerformed
        IndoorPatientItem ip= new IndoorPatientItem();
        ip.setVisible(true);
    }//GEN-LAST:event_indoor_patientActionPerformed

    private void outdoor_patientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outdoor_patientActionPerformed
        OutdoorPatientItem op = new OutdoorPatientItem();
        op.setVisible(true);
    }//GEN-LAST:event_outdoor_patientActionPerformed

    private void release_patientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_release_patientActionPerformed
        ReleasePatient rp =new ReleasePatient();
        rp.setVisible(true);
    }//GEN-LAST:event_release_patientActionPerformed

    private void parmanent_doctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parmanent_doctorActionPerformed
        DoctorEntryForm def = new DoctorEntryForm();
        def.setVisible(true);
    }//GEN-LAST:event_parmanent_doctorActionPerformed

    private void admin_entryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_entryActionPerformed
        AdministratorItem ai =new AdministratorItem();
        ai.setVisible(true);
    }//GEN-LAST:event_admin_entryActionPerformed

    private void search_docActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_docActionPerformed
        SearchDoctor sd=new SearchDoctor();
        sd.setVisible(true);
    }//GEN-LAST:event_search_docActionPerformed

    private void search_staffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_staffActionPerformed
        SearchStaff ss=new SearchStaff();
        ss.setVisible(true);
    }//GEN-LAST:event_search_staffActionPerformed

    private void Indoor_PatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Indoor_PatientActionPerformed
        SearchIndoorPatient sip=new SearchIndoorPatient();
        sip.setVisible(true);
    }//GEN-LAST:event_Indoor_PatientActionPerformed

    private void Outdoor_patientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Outdoor_patientActionPerformed
        SearchOutdoorPatient sop= new SearchOutdoorPatient();
        sop.setVisible(true);
    }//GEN-LAST:event_Outdoor_patientActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        IndoorPatientTable ipt =new IndoorPatientTable();
        ipt.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       OutdoorPatientTable opt = new OutdoorPatientTable();
       opt.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void doc_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_infoActionPerformed
        DoctorInformationTable dit= new DoctorInformationTable();
        dit.setVisible(true);
    }//GEN-LAST:event_doc_infoActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        BillGenerationForm bgf=new BillGenerationForm();
        bgf.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(base_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(base_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(base_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(base_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new base_window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Indoor_Patient;
    private javax.swing.JMenuItem Outdoor_patient;
    private javax.swing.JMenuItem aboutUsItem;
    private javax.swing.JMenuItem admin_entry;
    private javax.swing.JMenuItem doc_info;
    private javax.swing.JMenuItem indoor_patient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem outdoor_patient;
    private javax.swing.JMenuItem parmanent_doctor;
    private javax.swing.JMenuItem release_patient;
    private javax.swing.JMenuItem search_doc;
    private javax.swing.JMenuItem search_staff;
    private javax.swing.JMenuItem staff_entry;
    // End of variables declaration//GEN-END:variables


   // @Override
    //public void actionPerformed(ActionEvent event){
     //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
  //  }
}
